[tool.black]
target-version = ["py37"]

[tool.pylint.'MESSAGES CONTROL']
disable = [
    "R0902", # too-many-instance-attributes
    "R0903", # too-few-public-methods
    "R0911", # too-many-return-statements
    "R0912", # too-many-branches
    "R0913", # too-many-arguments
    "R0914", # too-many-locals
    "R0915", # too-many-statements
    "R1705", # no-else-return
    "C0103", # invalid-name
    "C0114", # missing-module-docstring
    "C0115", # missing-class-docstring
    "C0116", # missing-function-docstring
    "C0209", # consider-using-f-string
    "C0301", # line-too-long
    "W0401", # wilcard-import
    "W0511", # fixme
    "W0603", # global-statement
    "W0614", # unused-wildcard-import
    "W0702", # bare-except
    "W0703", # broad-except
    "W1514", # unspecified-encoding
]
