#!/bin/bash

PROJECT_HOME="/home/ajisoo/DiscordBot"
LOCAL="local"
PID_FILE="$LOCAL/pid"
LOG_FILE="$LOCAL/logs.txt"

cd "$PROJECT_HOME"

if test -e "$PID_FILE"; then
	old_pid=$(<"$PID_FILE")
	kill -9 "$old_pid"
	rm "$PID_FILE"
fi

git pull &>> "$LOG_FILE"

python3 bot.py &>> "$LOG_FILE" &
echo "$!" > "$PID_FILE"